# Generated by Django 5.0.2 on 2024-02-18 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Sub-Admin', 'Sub-Admin'), ('Staff', 'Staff')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='User_Authentication_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_authentication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
