# Generated by Django 5.0.2 on 2024-02-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_custom_user_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_authentication_model',
            name='login_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
