# Generated by Django 5.0.2 on 2024-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='image/bank_icons/')),
                ('qr_code', models.ImageField(upload_to='image/bank_qr_codes/')),
                ('account_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='image/mobile_wallet_icons/')),
                ('qr_code', models.ImageField(upload_to='image/mobile_wallet_qr_codes/')),
                ('account_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('payment_person', models.CharField(max_length=100)),
                ('payment_person_id', models.CharField(max_length=100)),
                ('check_number', models.CharField(max_length=100)),
                ('check_security_code', models.CharField(max_length=100)),
                ('currency_iso', models.CharField(max_length=3)),
                ('check_account', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
