# Generated by Django 5.0.2 on 2024-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='icon',
            field=models.ImageField(upload_to='image/bank_icons/'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='qr_code',
            field=models.ImageField(upload_to='image/bank_qr_codes/'),
        ),
        migrations.AlterField(
            model_name='blogcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/blog_images/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagefour',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagefourone',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagefourthree',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagefourtwo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagethree',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='three/image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagethreeone',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='three/image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagethreetwo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='three/image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagetwo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardhomepagetwoone',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/icons/'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/card_images/'),
        ),
        migrations.AlterField(
            model_name='company_member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/company-member/'),
        ),
        migrations.AlterField(
            model_name='global_location',
            name='flag_logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/global-location-flag/'),
        ),
        migrations.AlterField(
            model_name='homepage_segment',
            name='photo_or_video',
            field=models.FileField(blank=True, null=True, upload_to='image/segment/'),
        ),
        migrations.AlterField(
            model_name='mobilewallet',
            name='icon',
            field=models.ImageField(upload_to='image/mobile_wallet_icons/'),
        ),
        migrations.AlterField(
            model_name='mobilewallet',
            name='qr_code',
            field=models.ImageField(upload_to='image/mobile_wallet_qr_codes/'),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='image/notice-board/'),
        ),
        migrations.AlterField(
            model_name='order_card',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='image/order-card/'),
        ),
        migrations.AlterField(
            model_name='order_card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/order-card/'),
        ),
        migrations.AlterField(
            model_name='our_services',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/services-icons/'),
        ),
        migrations.AlterField(
            model_name='payment_logo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/payment-logo/'),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/socialmedia-icon/'),
        ),
        migrations.AlterField(
            model_name='support_company_logo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/comapny-logo/'),
        ),
        migrations.AlterField(
            model_name='technology_icon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/technology-icons/'),
        ),
        migrations.AlterField(
            model_name='websitebanner',
            name='image_and_video',
            field=models.FileField(blank=True, null=True, upload_to='image/banners/'),
        ),
        migrations.AlterField(
            model_name='websitelogo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/logo/'),
        ),
    ]
