# Generated by Django 5.0.2 on 2024-02-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IT_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/bank_icons/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='it/image/bank_qr_codes/')),
                ('account_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_BlogCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/blog_images/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageFourOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageFourThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageFourTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageThreeOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageThreeTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardHomepageTwoOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IT_CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/card_images/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Company_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/company-member/')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=600)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Global_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_logo', models.ImageField(blank=True, null=True, upload_to='it/image/global-location-flag/')),
                ('country_name', models.CharField(max_length=30)),
                ('office_address', models.CharField(max_length=400)),
                ('contact_details', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Homepage_Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_or_video', models.FileField(blank=True, null=True, upload_to='it/image/segment/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Live_Chat_Admin_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_live_chat_notification_sound', models.FileField(blank=True, null=True, upload_to='it/sound/admin_live_chat_notification_sound/')),
                ('admin_live_call_ringtone', models.FileField(blank=True, null=True, upload_to='it/sound/admin_live_call_ringtone/')),
                ('user_cannot_call_admin_sound', models.FileField(blank=True, null=True, upload_to='it/sound/user_cannot_call_admin_sound/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_MobileWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/mobile_wallet_icons/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='it/image/mobile_wallet_qr_codes/')),
                ('account_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Notice_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='it/image/notice-board/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Office_Address_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=140)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Office_Address_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=140)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IT_OfflineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('payment_receipt_person_name', models.CharField(max_length=100)),
                ('payment_receipt_person_id', models.CharField(max_length=100)),
                ('check_holder_name', models.CharField(max_length=100)),
                ('check_holder_gmail', models.EmailField(max_length=254)),
                ('check_holder_phone_number', models.CharField(max_length=14)),
                ('check_number', models.CharField(max_length=100)),
                ('check_security_code', models.CharField(max_length=100)),
                ('currency_iso', models.CharField(max_length=3)),
                ('check_amount', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Order_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/order-card/')),
                ('file', models.FileField(blank=True, null=True, upload_to='it/image/order-card/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Our_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/services-icons/')),
                ('title', models.CharField(max_length=500)),
                ('tags', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Payment_Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='it/image/payment-logo/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Security_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Social_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/socialmedia-icon/')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Support_Company_Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='it/image/comapny-logo/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IT_TimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('second', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IT_User_Order_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_chat_notification_tone', models.FileField(blank=True, null=True, upload_to='it/sound/order_chat_notification_tone/')),
                ('order_call_ringtone', models.FileField(blank=True, null=True, upload_to='it/sound/order_call_ringtone/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_User_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_entry_sound', models.FileField(blank=True, null=True, upload_to='it/sound/entry_sound/')),
                ('live_chat_talk_sound', models.FileField(blank=True, null=True, upload_to='it/sound/live_chat_talk_sound/')),
                ('live_chat_turned_off_sound', models.FileField(blank=True, null=True, upload_to='it/sound/live_chat_turned_off_sound/')),
                ('user_live_chat_notification_sound', models.FileField(blank=True, null=True, upload_to='it/sound/user_live_chat_notification_sound/')),
                ('user_live_call_ringtone', models.FileField(blank=True, null=True, upload_to='it/sound/user_live_call_ringtone/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_WebsiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('image_and_video', models.FileField(blank=True, null=True, upload_to='it/image/banners/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_WebsiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_1_Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('topic_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('footer_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_section_1_topics', to='it_dashboard.it_footer_section_1')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_2_Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('topic_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('footer_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_section_2_topics', to='it_dashboard.it_footer_section_2')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_3_Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('topic_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('footer_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_section_3_topics', to='it_dashboard.it_footer_section_3')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Technology_Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/technology-icons/')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='it_dashboard.it_technology')),
            ],
        ),
    ]
