# Generated by Django 5.0.2 on 2024-02-22 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civil_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_file', models.FileField(blank=True, null=True, upload_to='civil/order/project-file/')),
                ('related_file', models.FileField(blank=True, null=True, upload_to='civil/order/related-file/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment', 'Payment'), ('Waiting', 'Waiting'), ('Working', 'Working'), ('Complited', 'Complited'), ('Cancel', 'Cancel')], max_length=40)),
                ('piority', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('Emergency', 'Emergency')], max_length=40)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('BDT', 'BDT'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD')], max_length=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_online_deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_offline_deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_remain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_user_order', to='user.website_user')),
            ],
            options={
                'ordering': ['updated_date', 'created_date', 'delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Civil_Order_Admin_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box', models.TextField(blank=True, null=True)),
                ('file_or_image', models.FileField(blank=True, null=True, upload_to='civil/order/note-file/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_order_note', to='civil.civil_order')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_Order_Update_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='civil_order_update', to='civil.civil_order')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Civil_Order_User_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('educational_qualifications', models.TextField()),
                ('professional_details', models.TextField()),
                ('occupation', models.CharField(max_length=255)),
                ('work_experience', models.IntegerField()),
                ('skills', models.TextField()),
                ('interests', models.TextField()),
                ('hobbies', models.TextField()),
                ('profile_id', models.CharField(max_length=50)),
                ('application_date', models.DateField()),
                ('payment_currency', models.CharField(max_length=10)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='civil/order/user/')),
                ('user_signature', models.ImageField(blank=True, null=True, upload_to='civil/order/user/signature/')),
                ('company_signature', models.ImageField(blank=True, null=True, upload_to='civil/order/company/signature/')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='civil_order_user_information', to='civil.civil_order')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('order_profile_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_order_product', to='civil.civil_order_user_information')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_Order_Work_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='civil/order/work-update/')),
                ('files', models.FileField(blank=True, null=True, upload_to='civil/order/work-update/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_order_work_document', to='civil.civil_order')),
            ],
        ),
    ]
