# Generated by Django 5.0.2 on 2024-02-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil', '0004_rename_reason_civil_refund_reason_for_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civil_offlinepayment',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='civil_refund',
            name='currency',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='civil_refund',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
