# Generated by Django 5.0.2 on 2024-02-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil', '0006_remove_civil_order_user_information_payment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civil_order_user_information',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='civil_order_user_information',
            name='profile_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
