# Generated by Django 5.0.2 on 2024-02-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil', '0007_alter_civil_order_user_information_application_date_and_more'),
        ('civil_dashboard', '0002_civil_offlinecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civil_payment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='civil_bank', to='civil_dashboard.civil_bank'),
        ),
        migrations.AlterField(
            model_name='civil_payment',
            name='mobile_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='civil_mobile_wallet', to='civil_dashboard.civil_mobilewallet'),
        ),
    ]
