# Generated by Django 5.0.2 on 2024-02-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0003_it_refund_it_mobile_refund_it_bank_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_payment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='it_payment',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
