# Generated by Django 5.0.2 on 2024-02-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0005_rename_reason_it_refund_reason_for_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_offlinepayment',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
