# Generated by Django 5.0.2 on 2024-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Chat_Admin_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_live_chat_notification_sound', models.FileField(blank=True, null=True, upload_to='sound/admin_live_chat_notification_sound/')),
                ('admin_live_call_ringtone', models.FileField(blank=True, null=True, upload_to='sound/admin_live_call_ringtone/')),
                ('user_cannot_call_admin_sound', models.FileField(blank=True, null=True, upload_to='sound/user_cannot_call_admin_sound/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Order_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_chat_notification_tone', models.FileField(blank=True, null=True, upload_to='sound/order_chat_notification_tone/')),
                ('order_call_ringtone', models.FileField(blank=True, null=True, upload_to='sound/order_call_ringtone/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_entry_sound', models.FileField(blank=True, null=True, upload_to='sound/entry_sound/')),
                ('live_chat_talk_sound', models.FileField(blank=True, null=True, upload_to='sound/live_chat_talk_sound/')),
                ('live_chat_turned_off_sound', models.FileField(blank=True, null=True, upload_to='sound/live_chat_turned_off_sound/')),
                ('user_live_chat_notification_sound', models.FileField(blank=True, null=True, upload_to='sound/user_live_chat_notification_sound/')),
                ('user_live_call_ringtone', models.FileField(blank=True, null=True, upload_to='sound/user_live_call_ringtone/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sound',
            name='admin_call_ringtone',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='admin_chat_notification_sound',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='entry_sound',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='live_call_ringtone',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='live_chat_notification_sound',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='live_chat_talk_sound',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='live_chat_turned_off_sound',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='order_call_ringtone',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='order_chat_notification_tone',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='user_cannot_call_admin_sound',
        ),
        migrations.DeleteModel(
            name='Admin_Call_Ringtone',
        ),
        migrations.DeleteModel(
            name='Admin_Chat_Notification_Sound',
        ),
        migrations.DeleteModel(
            name='EntrySound',
        ),
        migrations.DeleteModel(
            name='Live_Call_Ringtone',
        ),
        migrations.DeleteModel(
            name='Live_Chat_Notification_Sound',
        ),
        migrations.DeleteModel(
            name='Live_Chat_Talk_Sound',
        ),
        migrations.DeleteModel(
            name='Live_Chat_Turned_Off_Sound',
        ),
        migrations.DeleteModel(
            name='Order_Call_Ringtone',
        ),
        migrations.DeleteModel(
            name='Order_Chat_Notification_Tone',
        ),
        migrations.DeleteModel(
            name='Sound',
        ),
        migrations.DeleteModel(
            name='User_Cannot_Call_Admin_Sound',
        ),
    ]
