# Generated by Django 5.0.2 on 2024-02-16 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=500)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Working', 'Working'), ('Complete', 'Complete'), ('Payment', 'Payment'), ('Delivery', 'Delivery'), ('Waiting', 'Waiting')], default='Pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_holder_email', models.EmailField(max_length=100)),
                ('account_phone_number', models.CharField(max_length=14)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('account_number', models.CharField(max_length=100)),
                ('account_info', models.CharField(max_length=100)),
                ('transaction_receipt', models.FileField(blank=True, null=True, upload_to='payment/transaction/')),
                ('order_ID', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_payment', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
