# Generated by Django 5.0.2 on 2024-02-18 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_file', models.FileField(blank=True, null=True, upload_to='static/project-file/')),
                ('related_file', models.FileField(blank=True, null=True, upload_to='static/project-file/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment', 'Payment'), ('Waiting', 'Waiting'), ('Working', 'Working'), ('Complited', 'Complited'), ('Cancel', 'Cancel')], max_length=40)),
                ('piority', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('Emergency', 'Emergency')], max_length=40)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('BDT', 'BDT'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD')], max_length=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_online_deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_offline_deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('money_left', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_date', 'created_date', 'delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Order_Update_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/message_images/')),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_update', to='order.order')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Order_Work_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/work-update/')),
                ('files', models.FileField(blank=True, null=True, upload_to='static/work-update/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_work_document', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box', models.TextField(blank=True, null=True)),
                ('file_or_image', models.FileField(blank=True, null=True, upload_to='static/note-file/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_note', to='order.order')),
            ],
        ),
    ]
