# Generated by Django 5.0.2 on 2024-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='money_left',
            new_name='total_amount_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_remain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
