# Generated by Django 5.0.2 on 2024-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Moblie Walet', 'Moblie Walet')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Cancel', 'Cancel'), ('Delivery', 'Delivery'), ('Waiting', 'Waiting'), ('Payment', 'Payment'), ('Working', 'Working')], default='Pending', max_length=20),
        ),
    ]
