# Generated by Django 5.0.2 on 2024-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_payment_payment_method_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Complete', 'Complete'), ('Working', 'Working'), ('Payment', 'Payment'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], default='Pending', max_length=20),
        ),
    ]
