# Generated by Django 5.0.2 on 2024-02-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_profit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
