# Generated by Django 5.0.2 on 2024-02-16 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Working', 'Working'), ('Complete', 'Complete'), ('Waiting', 'Waiting'), ('Delivery', 'Delivery'), ('Payment', 'Payment'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Bank_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_holder_email', models.EmailField(max_length=100)),
                ('account_phone_number', models.CharField(max_length=14)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('account_number', models.CharField(max_length=100)),
                ('account_info', models.CharField(max_length=100)),
                ('transaction_receipt', models.FileField(blank=True, null=True, upload_to='payment/transaction/')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_bank_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Banking_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_banking', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_holder_email', models.EmailField(max_length=100)),
                ('account_phone_number', models.CharField(max_length=14)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('account_number', models.CharField(max_length=100)),
                ('account_info', models.CharField(max_length=100)),
                ('transaction_receipt', models.FileField(blank=True, null=True, upload_to='payment/transaction/')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_mobile_bank_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
