# Generated by Django 5.0.2 on 2024-02-19 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_profit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_update_box',
            name='image',
        ),
        migrations.AddField(
            model_name='order_update_box',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='order/project-file/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='order/related-file/'),
        ),
        migrations.AlterField(
            model_name='order_update_box',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order_work_document',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='order/work-update/'),
        ),
        migrations.AlterField(
            model_name='order_work_document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order/work-update/'),
        ),
        migrations.AlterField(
            model_name='orderadminnote',
            name='file_or_image',
            field=models.FileField(blank=True, null=True, upload_to='order/note-file/'),
        ),
    ]
