# Generated by Django 5.0.2 on 2024-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Sub-Admin', 'Sub-Admin'), ('Staff', 'Staff')], max_length=50, null=True),
        ),
    ]
