# Generated by Django 5.0.2 on 2024-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0002_custom_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
